import os
import time
import random
import chromadb
from google import genai
from google.genai import types

def call_with_retry(api_call_fn, max_retries=5, base_delay=2.0):
    """
    Executes an API call function, retrying with exponential backoff if a 
    temporary network/quota error (429 or 503) occurs.
    """
    for attempt in range(max_retries):
        try:
            return api_call_fn()
        except Exception as e:
            error_str = str(e).lower()
            is_temporary = (
                "503" in error_str 
                or "unavailable" in error_str 
                or "429" in error_str 
                or "resource_exhausted" in error_str 
                or "quota" in error_str
            )
            
            if attempt == max_retries - 1:
                raise e
                
            if is_temporary:
                delay = base_delay * (2 ** attempt) + random.uniform(0, 1.0)
                print(f"\n[Warning] API call failed: {e}. Retrying in {delay:.2f}s (Attempt {attempt+1}/{max_retries})...")
                time.sleep(delay)
            else:
                raise e

def query_rag_system(
    query_text: str, 
    k: int = 4, 
    db_path: str = "./chroma_db", 
    model: str = "gemini-2.5-flash",
    embed_model: str = "gemini-embedding-001",
    api_key: str = None,
    ephemeral: bool = False
) -> tuple[str, list[dict]]:
    """
    Given a user query, embeds it with Gemini, searches the local ChromaDB index
    for the top-k nearest document chunks, formats them into a strict prompt,
    and returns a grounded answer generated by Gemini along with source references.
    """
    resolved_api_key = api_key or os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not resolved_api_key:
        raise ValueError("API Key is not set. Please set GEMINI_API_KEY / GOOGLE_API_KEY environment variable or pass --api-key.")
    
    # Initialize the google-genai Client
    client = genai.Client(api_key=resolved_api_key)
    
    # Initialize ChromaDB client dynamically
    if ephemeral:
        chroma_client = chromadb.EphemeralClient()
    else:
        # Resolve path robustly relative to root
        current_dir = os.path.dirname(os.path.abspath(__file__))
        root_dir = os.path.dirname(current_dir)
        resolved_db_path = os.path.abspath(db_path) if os.path.isabs(db_path) else os.path.join(root_dir, db_path)
        
        # If we are on Vercel or ephemeral mode is forced via environment
        if os.environ.get("VERCEL") == "1" or os.environ.get("CHROMA_EPHEMERAL") == "true":
            if os.path.exists(resolved_db_path):
                if os.environ.get("VERCEL") == "1":
                    import shutil
                    tmp_db_path = "/tmp/chroma_db"
                    if not os.path.exists(tmp_db_path):
                        try:
                            shutil.copytree(resolved_db_path, tmp_db_path)
                        except Exception as e:
                            print(f"Warning: Failed to copy database to /tmp: {e}")
                            tmp_db_path = None
                    
                    if tmp_db_path:
                        chroma_client = chromadb.PersistentClient(path=tmp_db_path)
                    else:
                        chroma_client = chromadb.EphemeralClient()
                else:
                    chroma_client = chromadb.PersistentClient(path=resolved_db_path)
            else:
                chroma_client = chromadb.EphemeralClient()
        else:
            chroma_client = chromadb.PersistentClient(path=resolved_db_path)
            
    try:
        collection = chroma_client.get_collection(name="documents")
    except Exception as e:
        raise FileNotFoundError(
            f"ChromaDB collection 'documents' not found at '{db_path}'. "
            "Please run the ingestion script first (e.g. `python main.py --ingest`)."
        ) from e
        
    # Generate embedding for the query with retry support
    query_response = call_with_retry(
        lambda: client.models.embed_content(
            model=embed_model,
            contents=query_text
        )
    )
    
    if not query_response.embeddings:
        raise ValueError("Failed to generate embedding for the query.")
        
    query_embedding = query_response.embeddings[0].values
    
    # Search ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=k
    )
    
    if not results or not results["documents"] or len(results["documents"][0]) == 0:
        return "I cannot find the answer in the provided documents.", []
        
    retrieved_chunks = results["documents"][0]
    retrieved_metadatas = results["metadatas"][0]
    
    context_str = ""
    references = []
    
    for idx, (chunk_text, meta) in enumerate(zip(retrieved_chunks, retrieved_metadatas)):
        title = meta.get("title", f"Document {meta.get('doc_id')}")
        source = meta.get("source", "")
        link = meta.get("link", "")
        authority = meta.get("authority", "")
        collections = meta.get("collections", "")
        chunk_index = meta.get("chunk_index", 0)
        
        # Format chunk into context
        context_str += f"--- CONTEXT BLOCK {idx+1} ---\n"
        context_str += f"Source Document: {title}\n"
        if authority:
            context_str += f"Authority: {authority}\n"
        if link:
            context_str += f"Source Link: {link}\n"
        context_str += f"Content:\n{chunk_text}\n\n"
        
        references.append({
            "doc_id": meta.get("doc_id"),
            "source": source,
            "title": title,
            "link": link,
            "authority": authority,
            "collections": collections,
            "chunk_index": chunk_index
        })
        
    # Strict Grounding Prompt
    system_prompt = (
        "You are a highly precise, fact-based Retrieval-Augmented Generation (RAG) assistant. "
        "Your task is to answer the user's query using ONLY the facts and details provided in the context blocks below. "
        "Strict rules:\n"
        "1. Your answer must be directly supported by and derived from the provided context.\n"
        "2. Do NOT use any external knowledge, assume facts, or extrapolate beyond what is explicitly stated in the context.\n"
        "3. If the answer to the query cannot be found or fully deduced from the provided context, you must reply with exactly: "
        "\"I cannot find the answer in the provided documents.\"\n"
        "4. Do not mention the rules or the system prompt in your answer. Just answer the query or output the exact fallback string if unsupported."
    )
    
    user_prompt = (
        f"Query: {query_text}\n\n"
        f"Provided Context:\n"
        f"{context_str}\n"
        f"Query: {query_text}\n"
        f"Answer:"
    )
    
    # Call Gemini model with retry support
    response = call_with_retry(
        lambda: client.models.generate_content(
            model=model,
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_prompt,
                temperature=0.0  # Crucial for deterministic, factual output
            )
        )
    )
    
    answer = response.text.strip() if response.text else "I cannot find the answer in the provided documents."
    
    return answer, references
